# -*- coding: utf-8 -*-
"""Copy of ML4VA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qgv6goWYSFPhcogS4_A5ty1Pm1vJGrrp
"""

from google.colab import drive
drive.mount('/content/drive')

# !pip install geopandas plotly --quiet
# !pip install tensorflow seaborn


import pandas as pd
import matplotlib.pyplot as plt
from prophet import Prophet
import matplotlib.pyplot as plt
import seaborn as sns

# Load each dataset
food_bank = pd.read_csv('va_food_banks.csv', dtype={"FIPS": str})
poverty = pd.read_csv('HDPulse_data_export.csv')
snap = pd.read_csv('Dec_2024_Participation_Report.csv', dtype={"FIPS": str})
unemployment = pd.read_csv('bls_unemployment_by_month_county.csv')
population = pd.read_csv('2010_2024_population.csv')
snap = snap.rename(columns={'PERSONS\n (TOTAL)': 'persons_total'})
food_bank.rename(columns={'pounds_of_food_distributed': 'food_distributed_pounds'}, inplace=True)

population['County'] = population['County'].str.lstrip('.').str.strip()
population['County'] = population['County'].str.split(',').str[0].str.strip()

# Preview each dataset
print("✅ Food Bank Data Sample:")
display(food_bank.head())

print("✅ Poverty Data Sample:")
display(poverty.head())

print("✅ SNAP Data Sample:")
display(snap.head(200))

print("✅ Unemployment Data Sample:")
display(unemployment.head())

print("✅ Population Data Sample:")
display(population.head())

food_bank = food_bank.dropna(subset=['Year', 'Month', 'FIPS', 'Locality', 'Pounds of Food Distributed'])

poverty = poverty.dropna(subset=['County', 'FIPS', 'People (Below Poverty)'])

snap = snap.dropna(subset=['LOCALITY', 'FIPS', 'persons_total'])

unemployment = unemployment.dropna(subset=['StateCode', 'CountyCode', 'Year', 'Period', 'Unemployment'])

population = population.dropna()

print("✅ Rows after dropping nulls:")
print(f"Food Bank: {len(food_bank)} rows")
print(f"Poverty: {len(poverty)} rows")
print(f"SNAP: {len(snap)} rows")
print(f"Unemployment: {len(unemployment)} rows")
print(f"Population: {len(population)} rows")

#Clean Food Bank Data
food_bank.columns = food_bank.columns.str.strip().str.lower().str.replace(" ", "_")
food_bank['date'] = pd.to_datetime(food_bank['year'].astype(str) + ' ' + food_bank['month'], format='%Y %B', errors='coerce')
food_bank['fips'] = '51' + food_bank['fips'].astype(str).str.zfill(3)

#Clean Poverty Data
poverty.columns = poverty.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("(", "").str.replace(")", "")
poverty['fips'] = poverty['fips'].astype(str).str.zfill(5)

#Clean SNAP Data
snap.columns = snap.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("\n", "_").str.replace("(", "").str.replace(")", "")
snap['fips'] = '51' + snap['fips'].astype(str).str.zfill(3)
snap['date'] = pd.to_datetime(snap['date'])


#Clean Unempoment Data
unemployment['month'] = unemployment['Period'].str.extract('M(\d+)', expand=False)
unemployment['month'] = pd.to_numeric(unemployment['month'], errors='coerce')
unemployment = unemployment.dropna(subset=['Year', 'month'])

unemployment['Year'] = unemployment['Year'].astype(int)
unemployment['month'] = unemployment['month'].astype(int)

unemployment = unemployment[(unemployment['month'] >= 1) & (unemployment['month'] <= 12)]

unemployment['date'] = pd.to_datetime(
    unemployment['Year'].astype(str) + '-' + unemployment['month'].astype(str).str.zfill(2) + '-01',
    errors='coerce'
)

unemployment['fips'] = unemployment['StateCode'].astype(str) + unemployment['CountyCode'].astype(str).str.zfill(3)

# display(unemployment.head())


# Standardize county and locality names for matching
population['county_clean'] = population['County'].str.lower().str.strip()
snap['locality_clean'] = snap['locality'].str.lower().str.strip()

# Create locality → FIPS lookup dictionary from SNAP data
locality_to_fips = snap.drop_duplicates(subset='locality_clean')[['locality_clean', 'fips']] \
                        .set_index('locality_clean')['fips'].to_dict()

# Map FIPS codes into the population dataset using the cleaned county names
population['fips'] = population['county_clean'].map(locality_to_fips)

print("✅ Food Bank Data Sample:")
display(food_bank.head())

print("✅ Poverty Data Sample:")
display(poverty.head())

print("✅ SNAP Data Sample:")
display(snap.head(200))

print("✅ Unemployment Data Sample:")
display(unemployment.head())

# 📦 Imports
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# --- Step 1: Merge Unemployment + SNAP ---
# Ensure consistent FIPS and datetime formats
unemployment['fips'] = unemployment['fips'].astype(str).str.zfill(5)
snap['fips'] = snap['fips'].astype(str).str.zfill(5)

unemployment['date'] = pd.to_datetime(unemployment['date'])
snap['date'] = pd.to_datetime(snap['date'])

# Select relevant columns
unemp_cols = ['fips', 'date', 'Unemployment']
snap_cols = ['fips', 'date', 'persons_total']

# Merge on date and FIPS
merged = pd.merge(unemployment[unemp_cols], snap[snap_cols], on=['fips', 'date'], how='inner')
merged = merged.dropna(subset=['Unemployment', 'persons_total'])

# --- Step 2: Melt and Clean Population Data ---
valid_years = [str(y) for y in range(2010, 2025)]
population_long = population.melt(
    id_vars=['County', 'fips'],
    value_vars=valid_years,
    var_name='year',
    value_name='population'
)

population_long['population'] = population_long['population'].str.replace(',', '', regex=False).astype(int)
population_long['year'] = population_long['year'].astype(int)
population_long['fips'] = population_long['fips'].astype(str).str.zfill(5)
population_long = population_long.dropna(subset=['fips'])

# --- Step 3: Merge Population into Merged ---
merged['year'] = merged['date'].dt.year.astype(int)
merged['fips'] = merged['fips'].astype(str).str.zfill(5)

# Drop old population column if it exists
if 'population' in merged.columns:
    merged = merged.drop(columns=['population'])

# Merge population
merged = pd.merge(
    merged,
    population_long[['fips', 'year', 'population']],
    on=['fips', 'year'],
    how='left'
)

# Drop missing population rows
merged = merged.dropna(subset=['population'])

# --- Step 4: Normalize Columns ---
merged['unemployment_rate_per_capita'] = merged['Unemployment'] / merged['population']
merged['snap_participation_per_capita'] = merged['persons_total'] / merged['population']

# --- Step 5: Filter for Specific Months ---
november_data = merged[(merged['date'].dt.year == 2024) & (merged['date'].dt.month == 11)]
december_data = merged[(merged['date'].dt.year == 2024) & (merged['date'].dt.month == 12)]
october_data = merged[(merged['date'].dt.year == 2024) & (merged['date'].dt.month == 10)]
september_data = merged[(merged['date'].dt.year == 2024) & (merged['date'].dt.month == 9)]

# --- Step 6: Plot Correlation Function ---
def plot_correlation_normalized(data, month_name):
    plt.figure(figsize=(10, 7))
    sns.regplot(
        x='unemployment_rate_per_capita',
        y='snap_participation_per_capita',
        data=data,
        scatter_kws={'alpha': 0.6}
    )

    corr = data['unemployment_rate_per_capita'].corr(data['snap_participation_per_capita'])
    plt.title(f'{month_name} 2024 (Normalized): Corr = {corr:.2f}')
    plt.xlabel('Unemployment per Capita')
    plt.ylabel('SNAP Participation per Capita')

    for _, row in data.iterrows():
        plt.text(
            row['unemployment_rate_per_capita'],
            row['snap_participation_per_capita'],
            str(row['fips']),
            fontsize=8,
            alpha=0.7
        )

    plt.grid(True)
    plt.tight_layout()
    plt.show()

# --- Step 7: Plot for All Months ---
plot_correlation_normalized(october_data, "October")
plot_correlation_normalized(november_data, "November")
plot_correlation_normalized(december_data, "December")
plot_correlation_normalized(september_data, "September")

# --- Optional: Preview the Final Merged Data ---
display(merged.head())

# # Filter for November and December 2024
# # Filter for specific months in 2024
# november_data = merged[(merged['date'].dt.year == 2024) & (merged['date'].dt.month == 11)]
# december_data = merged[(merged['date'].dt.year == 2024) & (merged['date'].dt.month == 12)]

# def plot_correlation_normalized(data, month_name):
#     plt.figure(figsize=(10, 7))

#     # Scatter plot with regression line
#     sns.regplot(
#         x='unemployment_rate_per_capita',
#         y='snap_participation_per_capita',
#         data=data,
#         scatter_kws={'alpha': 0.6}
#     )

#     # Calculate and display correlation
#     corr = data['unemployment_rate_per_capita'].corr(data['snap_participation_per_capita'])
#     plt.title(f'{month_name} 2024 (Normalized): Corr = {corr:.2f}')
#     plt.xlabel('Unemployment per Capita')
#     plt.ylabel('SNAP Participation per Capita')

#     # Optional: Add FIPS labels
#     for _, row in data.iterrows():
#         plt.text(
#             row['unemployment_rate_per_capita'],
#             row['snap_participation_per_capita'],
#             str(row['fips']),
#             fontsize=8,
#             alpha=0.7
#         )

#     plt.grid(True)
#     plt.tight_layout()
#     plt.show()

# plot_correlation_normalized(november_data, "November")
# plot_correlation_normalized(december_data, "December")

food_bank.rename(columns={'pounds_of_food_distributed': 'food_distributed_pounds'}, inplace=True)

# Extract month
unemployment['month'] = unemployment['date'].dt.month

# Compute average unemployment per calendar month
monthly_unemployment_avg = unemployment.groupby('month')['Unemployment'].mean().reset_index()
monthly_unemployment_avg.rename(columns={'Unemployment': 'avg_unemployment'}, inplace=True)


# Extract month
food_bank['month'] = food_bank['date'].dt.month

# Compute average food distributed per calendar month
monthly_food_avg = food_bank.groupby('month')['food_distributed_pounds'].mean().reset_index()
monthly_food_avg.rename(columns={'food_distributed_pounds': 'avg_food_distributed_pounds'}, inplace=True)


# Merge both monthly averages on month
unemp_food_corr_df = pd.merge(monthly_unemployment_avg, monthly_food_avg, on='month')

# Calculate correlation
unemp_food_corr = unemp_food_corr_df['avg_unemployment'].corr(unemp_food_corr_df['avg_food_distributed_pounds'])

# Display result
print(f"📈 Correlation between Average Monthly Unemployment and Food Distributed: {unemp_food_corr:.2f}")

# Extract month
snap['month'] = snap['date'].dt.month

# Compute average SNAP participants per calendar month
monthly_snap_avg = snap.groupby('month')['persons_total'].mean().reset_index()
monthly_snap_avg.rename(columns={'persons_total': 'avg_snap_participants'}, inplace=True)


# Merge with food data
snap_food_corr_df = pd.merge(monthly_snap_avg, monthly_food_avg, on='month')

# Calculate correlation
snap_food_corr = snap_food_corr_df['avg_snap_participants'].corr(snap_food_corr_df['avg_food_distributed_pounds'])

# Display result
print(f"📈 Correlation between Average Monthly SNAP Participants and Food Distributed: {snap_food_corr:.2f}")

import seaborn as sns
import matplotlib.pyplot as plt

# Plot 1: Unemployment vs Food Distributed
plt.figure(figsize=(10, 6))
sns.regplot(data=unemp_food_corr_df, x='avg_unemployment', y='avg_food_distributed_pounds')
plt.title(f'Avg Unemployment vs Food Distributed (Corr = {unemp_food_corr:.2f})')
plt.xlabel('Average Monthly Unemployment (All Counties)')
plt.ylabel('Average Monthly Food Distributed (Pounds)')
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot 2: SNAP Participants vs Food Distributed
plt.figure(figsize=(10, 6))
sns.regplot(data=snap_food_corr_df, x='avg_snap_participants', y='avg_food_distributed_pounds')
plt.title(f'Avg SNAP Participants vs Food Distributed (Corr = {snap_food_corr:.2f})')
plt.xlabel('Average Monthly SNAP Participants (All Counties)')
plt.ylabel('Average Monthly Food Distributed (Pounds)')
plt.grid(True)
plt.tight_layout()
plt.show()

import geopandas as gpd
import plotly.express as px

# --- Step 1: Create County-Level Aggregated Dataset ---

# Aggregate latest values for each county
latest_snap = snap[snap['date'].dt.month == 12]
latest_snap = latest_snap.sort_values('date').drop_duplicates('fips', keep='last')

latest_unemp = unemployment[unemployment['date'].dt.month == 12]
latest_unemp = latest_unemp.sort_values('date').drop_duplicates('fips', keep='last')

latest_food = food_bank[food_bank['date'].dt.month == 12]
latest_food = latest_food.sort_values('date').drop_duplicates('fips', keep='last')

# Merge all into one
county_stats = latest_snap[['fips', 'persons_total']].merge(
    latest_unemp[['fips', 'Unemployment']], on='fips', how='outer'
).merge(
    latest_food[['fips', 'food_distributed_pounds']], on='fips', how='outer'
).merge(
    poverty[['fips', 'people_below_poverty']], on='fips', how='left'
).merge(
    population_long[population_long['year'] == 2024][['fips', 'population']], on='fips', how='left'
)

# Drop rows with missing population
county_stats = county_stats.dropna(subset=['population'])

# --- Step 2: Normalize per capita ---
county_stats['unemployment_per_capita'] = county_stats['Unemployment'] / county_stats['population']
county_stats['snap_per_capita'] = county_stats['persons_total'] / county_stats['population']
county_stats['food_per_capita'] = county_stats['food_distributed_pounds'] / county_stats['population']
county_stats['poverty_per_capita'] = county_stats['people_below_poverty'] / county_stats['population']

# Drop rows with missing values in key indicators
county_stats = county_stats.dropna(subset=[
    'unemployment_per_capita', 'snap_per_capita', 'food_per_capita', 'poverty_per_capita'
])

# --- Step 3: Define High-Need Criteria ---
# Use 75th percentile threshold for each metric
unemp_thresh = county_stats['unemployment_per_capita'].quantile(0.75)
snap_thresh = county_stats['snap_per_capita'].quantile(0.75)
food_thresh = county_stats['food_per_capita'].quantile(0.75)
poverty_thresh = county_stats['poverty_per_capita'].quantile(0.75)

# Classify: High-Need if 2 or more indicators are above threshold
county_stats['high_unemp'] = county_stats['unemployment_per_capita'] > unemp_thresh
county_stats['high_snap'] = county_stats['snap_per_capita'] > snap_thresh
county_stats['high_food'] = county_stats['food_per_capita'] > food_thresh
county_stats['high_poverty'] = county_stats['poverty_per_capita'] > poverty_thresh

county_stats['high_need_score'] = (
    county_stats[['high_unemp', 'high_snap', 'high_food', 'high_poverty']].sum(axis=1)
)

county_stats['high_need'] = county_stats['high_need_score'] >= 2

# --- Step 4: Add County Names ---
fips_to_locality = snap.drop_duplicates(subset='fips')[['fips', 'locality']].set_index('fips')['locality'].to_dict()
county_stats['county_name'] = county_stats['fips'].map(fips_to_locality)

# --- Step 5: Display Results ---
# print("🧾 High-Need County Classification:\n")
# for _, row in county_stats.sort_values('high_need_score', ascending=False).iterrows():
#     print(f"{row['county_name']}: {'HIGH-NEED' if row['high_need'] else 'Not High-Need'}")

# --- Step 6: Plot on Map ---

# Load US counties shapefile from geopandas
gdf = gpd.read_file("https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json")

# Plot using Plotly Choropleth
fig = px.choropleth(
    county_stats,
    geojson="https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json",
    locations='fips',
    color='high_need',
    color_continuous_scale=['#d3d3d3', '#ff4136'],
    scope="usa",
    labels={'high_need': 'High Need'},
    title='🗺️ Virginia County-Level High-Need Classification (Dec 2024)'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r":0,"t":50,"l":0,"b":0})
fig.show()

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
import seaborn as sns

# --- Step 1: Monthly Averages ---

# Extract month
food_bank['month'] = food_bank['date'].dt.month
snap['month'] = snap['date'].dt.month
unemployment['month'] = unemployment['date'].dt.month

# Compute monthly averages
monthly_food = food_bank.groupby('month')['food_distributed_pounds'].mean().reset_index()
monthly_snap = snap.groupby('month')['persons_total'].mean().reset_index()
monthly_unemp = unemployment.groupby('month')['Unemployment'].mean().reset_index()

# Use average population and poverty across all counties (2024)
avg_population = population_long[population_long['year'] == 2024]['population'].mean()
avg_poverty = poverty['people_below_poverty'].mean()

# --- Step 2: Create Modeling Dataset with 12 Months ---

df_model = pd.merge(monthly_food, monthly_snap, on='month', how='inner')
df_model = pd.merge(df_model, monthly_unemp, on='month', how='inner')

# Add static columns
df_model['population'] = avg_population
df_model['poverty'] = avg_poverty

# Normalize features
df_model['snap_per_capita'] = df_model['persons_total'] / df_model['population']
df_model['unemp_per_capita'] = df_model['Unemployment'] / df_model['population']
df_model['poverty_per_capita'] = df_model['poverty'] / df_model['population']

# Lag feature: previous month's food (circular for demo)
df_model = df_model.sort_values('month')
df_model['prev_food'] = df_model['food_distributed_pounds'].shift(1)
df_model['prev_food'].fillna(df_model['food_distributed_pounds'].mean(), inplace=True)

plt.figure(figsize=(10, 8))
sns.heatmap(df_model.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("📊 Correlation Matrix of All Model Variables")
plt.tight_layout()
plt.show()

# --- Step 3: Train Model ---
features = ['month', 'snap_per_capita', 'unemp_per_capita', 'poverty_per_capita', 'prev_food']
X = df_model[features]
y = df_model['food_distributed_pounds']

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X, y)


importances = model.feature_importances_
feat_imp = pd.DataFrame({'feature': features, 'importance': importances})
plt.figure(figsize=(8, 5))
sns.barplot(data=feat_imp, x='importance', y='feature')
plt.title("🔍 Feature Importance for Predicting Food Distribution")
plt.tight_layout()
plt.show()

# --- Step 4: Predict for Typical Year ---
df_model['predicted_food'] = model.predict(X)

from sklearn.metrics import r2_score, mean_squared_error

r2 = r2_score(y, df_model['predicted_food'])
rmse = mean_squared_error(y, df_model['predicted_food'], squared=False)

print(f"🔢 R² Score: {r2:.2f}")
print(f"🔢 RMSE: {rmse:,.0f} lbs")

# --- Step 5: Display and Plot ---
print("\n📅 Predicted Monthly Food Distribution (Synthetic Year):")
for i, row in df_model.iterrows():
    month_name = pd.to_datetime(f'2025-{int(row["month"]):02d}-01').strftime('%B')
    print(f"{month_name}: {row['predicted_food']:,.0f} lbs")

# --- Step 6: Plot ---
plt.figure(figsize=(10, 6))
sns.lineplot(data=df_model, x='month', y='food_distributed_pounds', label='Actual Avg')
sns.lineplot(data=df_model, x='month', y='predicted_food', label='Predicted')
plt.xticks(ticks=range(1,13), labels=[
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
])
plt.title("📦 Predicted vs Actual Avg Monthly Food Distribution")
plt.xlabel("Month")
plt.ylabel("Food Distributed (Pounds)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# # --- Step 0: Define Forecast Horizon ---
# forecast_years = list(range(2025, 2035))  # 10 years: 2025–2034

# # --- Step 1: Forecast Population for 10 Years ---

# future_pop = []

# for fips in pop_df['fips'].unique():
#     county_data = pop_df[pop_df['fips'] == fips].copy()
#     if len(county_data) >= 4:
#         last_3 = county_data.tail(3)['population_scaled'].values
#         for year in forecast_years:
#             pred_scaled = model_pop.predict(last_3.reshape(1, -1), verbose=0)[0][0]
#             pred = scaler_pop.inverse_transform([[pred_scaled]])[0][0]
#             future_pop.append({'fips': fips, 'year': year, 'population': int(pred)})
#             last_3 = np.append(last_3[1:], pred_scaled)

# future_pop_df = pd.DataFrame(future_pop)

# # --- Step 2: Forecast Unemployment for 10 Years (monthly) ---

# future_unemp = []

# for fips in unemp_df['fips'].unique():
#     county_data = unemp_df[unemp_df['fips'] == fips].copy()
#     if len(county_data) >= 4:
#         last_3 = county_data.tail(3)['unemp_scaled'].values
#         for year in forecast_years:
#             for month in range(1, 13):
#                 pred_scaled = model_unemp.predict(last_3.reshape(1, -1), verbose=0)[0][0]
#                 pred = scaler_unemp.inverse_transform([[pred_scaled]])[0][0]
#                 future_unemp.append({'fips': fips, 'year': year, 'month': month, 'Unemployment': pred})
#                 last_3 = np.append(last_3[1:], pred_scaled)

# future_unemp_df = pd.DataFrame(future_unemp)

# # --- Step 3: Prepare Food Prediction Inputs ---

# # Merge population and unemployment
# food_input = future_unemp_df.merge(future_pop_df, on=['fips', 'year'], how='left')

# # Merge static SNAP and poverty data
# food_input = food_input.merge(snap_avg, on='fips', how='left')
# food_input = food_input.merge(poverty_avg, on='fips', how='left')

# # Drop missing
# food_input = food_input.dropna()

# # Create per capita features
# food_input['snap_per_capita'] = food_input['persons_total'] / food_input['population']
# food_input['unemp_per_capita'] = food_input['Unemployment'] / food_input['population']
# food_input['poverty_per_capita'] = food_input['people_below_poverty'] / food_input['population']

# # Prepare input features
# food_input['month'] = food_input['month'].astype(int)
# X_future = food_input[['month', 'snap_per_capita', 'unemp_per_capita', 'poverty_per_capita']]

# # --- Step 4: Train Food Needs Model (Same as Before) ---

# X_food = hist_input[['month', 'snap_per_capita', 'unemp_per_capita', 'poverty_per_capita']]
# y_food = hist_input['food_distributed_pounds']

# model_food = Sequential([
#     Dense(64, activation='relu', input_shape=(4,)),
#     Dropout(0.2),
#     Dense(32, activation='relu'),
#     Dense(1)
# ])
# model_food.compile(optimizer='adam', loss='mse')
# model_food.fit(X_food, y_food, epochs=100, verbose=1)

# # --- Step 5: Predict Future Food Needs ---

# food_input['predicted_food'] = model_food.predict(X_future, verbose=1)

# # --- Step 6: Adjust to Avoid High-Need Counties ---

# # Define high-need threshold (e.g., 75% of historical average)
# county_avg_food = hist_input.groupby('fips')['food_distributed_pounds'].mean().reset_index()
# county_avg_food.rename(columns={'food_distributed_pounds': 'food_distributed_pounds_avg'}, inplace=True)

# food_input = food_input.merge(county_avg_food, on='fips', how='left')

# # Ensure predicted food ≥ 75% of historical average
# food_input['adjusted_food'] = food_input.apply(
#     lambda row: max(row['predicted_food'], 0.75 * row['food_distributed_pounds_avg']), axis=1
# )

# # --- Step 7: Optional Visualization ---

# random_fips = random.sample(list(food_input['fips'].unique()), 3)

# for fips in random_fips:
#     county_data = food_input[food_input['fips'] == fips]
#     county_data = county_data.sort_values(['year', 'month'])
#     plt.figure(figsize=(10, 4))
#     sns.lineplot(x=range(len(county_data)), y=county_data['adjusted_food'])
#     plt.title(f"📦 Predicted Food Needed: {fips} (2025–2034)")
#     plt.xlabel("Month Index (120 months)")
#     plt.ylabel("Food (lbs)")
#     plt.grid(True)
#     plt.tight_layout()
#     plt.show()

from prophet import Prophet

prophet_df = df_model[['month', 'food_distributed_pounds']].copy()
prophet_df['ds'] = pd.date_range(start='2024-01-01', periods=12, freq='MS')
prophet_df['y'] = prophet_df['food_distributed_pounds']

m = Prophet()
m.fit(prophet_df[['ds', 'y']])
future = m.make_future_dataframe(periods=3, freq='M')
forecast = m.predict(future)

fig = m.plot(forecast)
plt.title("📈 Prophet Forecast: Food Distribution")
plt.tight_layout()
plt.show()